"""Text feature construction."""

from text_factor_lab.features.matrix_store import (
    FeatureMatrixIndexRecord,
    FeatureMatrixStoreResult,
    build_tfidf_matrix_store,
    write_feature_matrix_index_json,
)
from text_factor_lab.features.text import (
    DEFAULT_FINANCIAL_DICTIONARIES,
    DICTIONARY_FEATURE_VERSION,
    TFIDF_FEATURE_VERSION,
    DocumentText,
    FeatureBuildResult,
    build_dictionary_feature_manifests,
    build_dictionary_tone_features,
    build_feature_input_hashes,
    build_metadata_features,
    build_tfidf_features,
    document_id_from_label_id,
    load_document_texts,
    read_document_manifest_jsonl,
    read_parsed_sections_jsonl,
    read_split_assignments_jsonl,
    tokenize,
    write_feature_manifest_json,
    write_features_jsonl,
    write_vocabulary_json,
)

__all__ = [
    "DEFAULT_FINANCIAL_DICTIONARIES",
    "DICTIONARY_FEATURE_VERSION",
    "TFIDF_FEATURE_VERSION",
    "DocumentText",
    "FeatureBuildResult",
    "FeatureMatrixIndexRecord",
    "FeatureMatrixStoreResult",
    "build_metadata_features",
    "build_dictionary_feature_manifests",
    "build_dictionary_tone_features",
    "build_feature_input_hashes",
    "build_tfidf_matrix_store",
    "build_tfidf_features",
    "document_id_from_label_id",
    "load_document_texts",
    "read_document_manifest_jsonl",
    "read_parsed_sections_jsonl",
    "read_split_assignments_jsonl",
    "tokenize",
    "write_feature_manifest_json",
    "write_feature_matrix_index_json",
    "write_features_jsonl",
    "write_vocabulary_json",
]

